;BEWARE! Editing this file manually can unlock quite a few skinning features, but it can also break. EVERYTHING.

[Variables]
Imagedir=#SKINSPATH#\WP7\Common\Panel\Default
ColorSkin=27,161,226
ColorSkin2=143,191,38
ColorSkinHover=255,0,255
Opacity=255
Opacity2=255
Opacitydarker=255
TextColor=255,255,255
TextColor2=255,255,255
TextItemAccentColor=27,161,226
Shadow=none
Overlay=none
OverlayDark=smooth
overlaydarkalpha=1
bordercolor=255,255,255
align=left
darkcolor=41,41,41
darkercolor=11,11,11
xposition=18.75
Shape=default
ItemShadow=1
ItemShadowColor=0,0,0
ItemShadowOffsetY=+1
ItemShadowOffsetX=+0
TextItemShadow=1
TextItemShadowColor=0,0,0
bevel=0
rotationangle=0
rotationangle1=0
rotationangle2=0
textangle=0
FontType=Segoe WP Semibold
FontTypeWP=Segoe WP
FontFaceUI=Segoe UI
FontFaceLight=Segoe UI Light
loadingbg=0,0,0,192
hideloadingtext=0

;defaults:
;FontType=Segoe WP Semibold
;FontTypeWP=Segoe WP
;FontFaceUI=Segoe UI
;FontFaceLight=Segoe UI Light
