[Variables]
AppName1=Mozilla Firefox
AppAction1=firefox.exe
AppName2=Notepad
AppAction2=notepad.exe
AppName3=Microsoft Word
AppAction3=winword.exe
AppName4=Media Player
AppAction4=wmplayer.exe
AppName5=Windows Explorer
AppAction5=explorer.exe

hub1name=#Time#
hub2name=#Weather#
hub3name=#Mail#

FolderName1=User Folder
FolderAction1=%USERPROFILE%
FolderName2=Desktop
FolderAction2=%USERPROFILE%\Desktop
FolderName3=Pictures
FolderAction3=%USERPROFILE%\Pictures
FolderName4=Documents
FolderAction4=%USERPROFILE%\Documents
FolderName5=Program Files
FolderAction5=%PROGRAMFILES%

SidebarColor=30,30,30,220
TextColor=240,240,240
width=300
Blur=1

Hub1=Time
Hub2=Weather
Hub3=Mail
UserName=%USERNAME%
