[Calc10]
Measure=Calc
Formula=(0.02*#Height#+8)

[Calc30]
Measure=Calc
Formula=(0.16*#Height#+7)

[Calc40]
Measure=Calc
Formula=(0.29*#Height#-1)

[Calc50]
Measure=Calc
Formula=(0.3*#Height#+5)

[Calc60]
Measure=Calc
Formula=(0.42*#Height#-2)

[Calc70]
Measure=Calc
Formula=(0.45*#Height#+3)

[Calc80]
Measure=Calc
Formula=(0.55*#Height#-3)

[Calc90]
Measure=Calc
Formula=(0.59*#Height#+2)

[Calc100]
Measure=Calc
Formula=(0.68*#Height#-4)

[Calc110]
Measure=Calc
Formula=(0.72*#Height#+3)

[Calc120]
Measure=Calc
Formula=(0.78*#Height#-2)

[Calc130]
Measure=Calc
Formula=(0.86*#Height#+2)

[Calc140]
Measure=Calc
Formula=(0.94*#Height#-6)