[Variables]
Name1=Internet
Action1=http://google.com
Name2=Pictures
Action2=%USERPROFILE%\Pictures
Name3=Control
Action3=%WINDIR%\system32\control.exe
Name4=Games
Action4=shell:games
Name5=Log off
Action5=logoff.lnk
Show3More=1

Name6=Music
Action6=%USERPROFILE%\Music

Name7=YouTube
Action7=http://youtube.com

Name8=Notepad
Action8=notepad.exe

FontFace=#FontFaceLight#
Iconvisibility=180
Padding=9
