[Variables]


[StartButton]
X=0
Y=(#menuheight#+#movestart#-48)
w=48
h=48

ImageName=#currentpath#\skins\default\start.png

[StartButtonH]
ImageName=#currentpath#\skins\default\starth.png


[MainBackground]
X=0
Y=0
w=410
h=#MenuHeight#
ScaleMargins=9,9,150,9
ImageName=#currentpath#\skins\default\bg.png
solidcolor=40,40,40

[ProgramsList]
X=9
Y=9
w=250
h=(#MenuHeight#-18)
solidcolor=0,0,255,1

[SearchBackground]
X=9
Y=446
w=252
h=45
ImageName=#currentpath#\skins\default\search.png
ScaleMargins=14,9,18,9


[SearchField]
X=23
Y=457
w=222
h=22
solidcolor=0,0,0,1

[PowerButtonBG]
X=273
Y=457
w=72
h=22
ImageName=#currentpath#\skins\default\Button.png
ScaleMargins=3,3,3,3

[PowerButton]
X=275
Y=456
w=66
h=16
FontColor=255,255,255
Antialias=1
FontFace=Segoe UI
FontSize=9
Padding=3,3,3,3
ImageName=#currentpath#\skins\default\Button.png
ScaleMargins=3,3,3,3



[PowerButtonArrow]
X=R
Y=456
w=22
h=22
ButtonImage=#currentpath#\skins\default\Arrow.png

[RightListFirst]
y=10

[RightList]
w=120
h=15
solidcolor=0,0,0,1
x=266
y=8R
FontColor=255,255,255
Antialias=1
FontFace=Segoe UI
FontSize=9
Padding=8,8,8,8

[RightListSeparator]
ImageName=#currentpath#\skins\default\separator.png
w=124
h=12
solidcolor=0,0,0,1
x=276
y=R


[LeftIconFirst]
y=17


[LeftIcon]
w=32
h=32
solidcolor=0,255,0,1
x=17
y=9R
Antialias=1


[LeftListFirst]
y=17

[LeftList]
w=150
h=17
solidcolor=0,255,255,1
x=17
y=8R
Antialias=1
FontColor=0,0,0
Antialias=1
FontFace=Segoe UI
FontSize=9
Padding=37,8,8,8






