[Variables]
Name1=Reddit
Action1=http://reddit.com
Name2=Minecraft
Action2=%AppData%\Roaming\.minecraft\Minecraft.exe
Name3=Computer
Action3="%SystemRoot%\explorer.exe" /E,::{20D04FE0-3AEA-1069-A2D8-08002B30309D}"
Name4=CMD
Action4="cmd.exe"
Name5=Lock PC
Action5=Lock.lnk
FontFace=#FontFaceLight#
iconvisibility=180
Padding=9
Show3More=1

Name6=Videos
Action6=%USERPROFILE%\Videos

Name7=Twitch
Action7=http://twitch.com

Name8=Calculator
Action8=calc.exe