[Variables]
Location1=Photoshop.exe
Icon1=#@#\Graphics\Panels\Adobe\Seperate\photoshop\icon2.png
Text

Location2=flashpro.exe
Icon2=#@#\Graphics\Panels\Adobe\Seperate\flashpro\icon2.png
Text

Location3=illustrator.exe
Icon3=#@#\Graphics\Panels\Adobe\Seperate\illustrator\icon2.png
Text

Location4=fireworks.exe
Icon4=#@#\Graphics\Panels\Adobe\Seperate\fireworks\icon2.png
Text

Location5=dreamweaver.exe
Icon5=#@#\Graphics\Panels\Adobe\Seperate\dreamweaver\icon2.png
Text

Location6=premierepro.exe
Icon6=#@#\Graphics\Panels\Adobe\Seperate\premierepro\icon2.png
Text

;[Variables]
;Location1=Photoshop.exe
;Icon1=photoshop\icon.png
;Location2=flashpro.exe
;Icon2=flashpro\icon.png
;Location3=illustrator.exe
;Icon3=illustrator\icon.png
;Location4=fireworks.exe
;Icon4=fireworks\icon.png
;Location5=dreamweaver.exe
;Icon5=dreamweaver\icon.png
;Location6=premierepro.exe
;Icon6=premierepro\icon.png
