[Variables]
Title=#Finance#
action=www.google.com/finance

Quote1=http://www.google.com/finance?q=INDEXBOM:AAPL
Quote2=http://www.google.com/finance?q=INDEXDJX:.DJI
Quote3=http://www.google.com/finance?q=INDEXNASDAQ%3A.IXIC
Quote4=http://www.google.com/finance?q=NASDAQ%3AMSFT
Quote5=http://www.google.com/finance?q=NASDAQ%3AHANS
Quote6=http://www.google.com/finance?q=NYSE%3AHYC
Quote7=http://www.google.com/finance?q=NYSE%3ATHI
Number1=AAPL
Number2=DOW JONES
Number3=NASDAQ
Number4=MSFT
Number5=HANS
Number6=HYC
Number7=THI
Update_Spd=1800
UpColour=50,150,50
DownColour=200,50,50
YGap=20r
GET=(?siU)<span id="ref.*">(.*)<.*class="ch.*".*class="ch(.*)".*id="ref.*">(.*)<.*id="ref.*">(.*)<
