[Variables]
MenuHeight=500
ProgramIcon1=icons\chrome.png
ProgramName1=Google Chrome
ProgramAction1=chrome.exe

ProgramIcon2=icons\notepad.png
ProgramName2=Notepad
ProgramAction2=notepad.exe

ProgramIcon3=icons\mspaint.png
ProgramName3=Paint
ProgramAction3=mspaint.exe

ProgramIcon4=icons\wmp.png
ProgramName4=Windows Media Player
ProgramAction4=wmplayer.exe

ProgramIcon5=icons\photoshop.png
ProgramName5=Adobe Photoshop
ProgramAction5=photoshop.exe

ProgramIcon6=icons\uTorrent.png
ProgramName6=uTorrent
ProgramAction6=uTorrent.exe

ProgramIcon7=
ProgramName7=
ProgramAction7=

ProgramIcon8=
ProgramName8=
ProgramAction8=


ProgramIcon9=
ProgramName9=
ProgramAction9=


ProgramIcon10=
ProgramName10=
ProgramAction10=



