[variables]
NowPlaying=listen.pls
PathToVLC="C:\Program Files\VideoLAN\VLC\vlc.exe"
Station1Link=977Hits.pls
Station1Title=".977 - All Hits"
Station2Link=SkyFMHits.pls
Station2Title="Sky FM - Hits"
Station3Link=SkyFM70s.pls
Station3Title="Sky FM - The 70's"
Station4Link=97780s.pls
Station4Title=".977 - The 80's"
Station5Link=1FM90s.pls
Station5Title="1 FM - The 90's"
Station6Link=181Alternative.pls
Station6Title="181 - Alternative"
Station7Link=181ClassicRock.pls
Station7Title="181 - Classic Rock"
Station8Link=RadioParadise.pls
Station8Title="Paradise Radio"
RadioScreenColor=

;change pathtoVLC to your path if it doesnt work
;click the help button for more info on this
