# PANEL METRICS

Federal regulations require us to warn you that changing these settings may ruin one or all of your Panels. Careful now.
Changes take effect after saving this file and refreshing items manually.

[Variables]
Imagedir=#@#Common\Panel\Rounded
Overlay=Aero

Globalblurenable=1
Blurtype=2
Blurcornerradius=5
Padding=0

ColorSkin=20,150,220
ColorSkin2=143,191,38

Opacity=1
Opacity2=255

TextColor=255,255,255
TextColor2=255,255,255


PanelTitleOpacity=255
Shadow=shadow
ItemShadowColor=0,0,0,100
Align=left
Xposition=15
DefaultFontSize=(#Height#/15-1)
Yposition=1.2

FontType=Segoe WP Semibold
FontTypeWP=Segoe WP
FontFaceUI=Segoe UI
FontFaceLight=Segoe WP Light


