;BEWARE! Editing this file manually can unlock quite a few skinning features, but it can also break. EVERYTHING.

[Variables]
arrowcolor=255,255,255
DefaultFontSize=(#Height#/15-1)
yposition=1.2
globalblurenable=1
blurtype=1
blurcornerradius=0
Padding=0
Imagedir=#@#Common\Panel\Default
ColorSkin=27,161,226
ColorSkin2=143,191,38
ColorSkinHover=255,0,255
Opacity=220
Opacity2=255
Opacitydarker=255
TextColor=255,255,255
TextColor2=255,255,255
TextItemAccentColor=27,161,226
Shadow=shadow
PanelTitleOpacity=255
ItemShadowColor=0,0,0,50
Overlay=W8
OverlayDark=smooth
overlaydarkalpha=1
bordercolor=255,255,255
align=left
darkcolor=41,41,41
darkercolor=11,11,11
xposition=15
Shape=default
ItemShadow=1
ItemShadowOffsetY=+1
ItemShadowOffsetX=+0
TextItemShadow=1
TextItemShadowColor=0,0,0
bevel=0
rotationangle=0
rotationangle1=0
rotationangle2=0
textangle=0
FontType=Segoe WP Semibold
FontTypeWP=Segoe WP
FontFaceUI=Segoe UI
FontFaceLight=Segoe WP Light
loadingbg=0,0,0,192
hideloadingtext=0

;defaults:
;FontType=Segoe WP Semibold
;FontTypeWP=Segoe WP
;FontFaceUI=Segoe UI
;FontFaceLight=Segoe UI Light
