# PANEL METRICS

[Variables]
Imagedir=#@#Common\Panel\Default
Overlay=none

Globalblurenable=1
Blurtype=1
Blurcornerradius=0
Padding=0

ColorSkin=30,30,30
ColorSkin2=50,50,50

Opacity=175
Opacity2=255

TextColor=255,255,255
TextColor2=254,254,254


PanelTitleOpacity=255
Shadow=shadow
ItemShadowColor=0,0,0,20
Align=left
Xposition=15
DefaultFontSize=(#Height#/15)
Yposition=1.2

FontType=Segoe WP Semibold
FontTypeWP=Segoe WP
FontFaceUI=Segoe UI
FontFaceLight=Segoe WP Light
win10blur=none
metric=1
PanelLabels=0
