# PANEL METRICS

[Variables]
Imagedir=#@#Common\Panel\Fancy
Overlay=Fancy

Globalblurenable=0
Blurtype=1
Blurcornerradius=0
Padding=0

ColorSkin=21,160,220
ColorSkin2=143,191,38

Opacity=255
Opacity2=255

SkinIconTint=255,255,255
TextColor=255,255,255
TextColor2=255,255,255


PanelTitleOpacity=255
Shadow=none
ItemShadowColor=0,0,0,50
Align=left
Xposition=15
DefaultFontSize=(#Height#/15-1)
Yposition=1.2

FontType=Segoe WP Semibold
FontTypeWP=Segoe WP
FontFaceUI=Segoe UI
FontFaceLight=Segoe WP Light