# PANEL METRICS

[Variables]
Imagedir=#@#Common\Panel\Default
Overlay=office

Globalblurenable=0
Blurtype=1
Blurcornerradius=0
Padding=0

PanelIconTint=66,66,65
ColorSkin=21,160,220
ColorSkin2=143,191,38

Opacity=1
Opacity2=255

SkinIconTint=30,30,30
TextColor=255,255,255
TextColor2=80,80,80


PanelTitleOpacity=255
Shadow=none
ItemShadowColor=0,0,0,50
Align=left
Xposition=15
DefaultFontSize=(#Height#/15-1)
Yposition=1.2

FontType=Segoe WP Semibold
FontTypeWP=Segoe WP
FontFaceUI=Segoe UI
FontFaceLight=Segoe WP Light