# PANEL METRICS

[Variables]
Imagedir=#@#Common\Panel\Rounded
Overlay=permafrost

Globalblurenable=1
Blurtype=2
Blurcornerradius=7
Padding=0

ColorSkin=255,255,255
ColorSkin2=143,191,38

Opacity=1
Opacity2=255

TextColor=255,255,255
TextColor2=50,50,50
SkinIconTint=50,50,50


PanelTitleOpacity=255
Shadow=shadow
ItemShadowColor=0,0,0,1
Align=left
Xposition=15
DefaultFontSize=(#Height#/15-1)
Yposition=1.2

FontType=Segoe WP Semibold
FontTypeWP=Segoe WP
FontFaceUI=Segoe UI
FontFaceLight=Segoe WP Light