# PANEL METRICS

[Variables]
Imagedir=#@#Common\Panel\Default
Overlay=Sky

Globalblurenable=0
Blurtype=1
Blurcornerradius=0
Padding=0

ColorSkin=100,100,100
ColorSkin2=143,191,38

Opacity=255
Opacity2=255

TextColor=255,255,255
TextColor2=0,46,81
SkinIconTint=0,46,81


PanelTitleOpacity=255
Shadow=none
ItemShadowColor=0,0,0,50
Align=left
Xposition=15
DefaultFontSize=(#Height#/15-1)
Yposition=1.2

FontType=Segoe WP Semibold
FontTypeWP=Segoe WP
FontFaceUI=Segoe UI
FontFaceLight=Segoe WP Light