# PANEL METRICS

[Variables]
Imagedir=#@#Common\Panel\Default
Overlay=W8

Globalblurenable=1
Blurtype=1
Blurcornerradius=0
Padding=3

ColorSkin=255,255,255
ColorSkin2=143,191,38

Opacity=30
Opacity2=255

TextColor=255,255,255
TextColor2=255,255,255


PanelTitleOpacity=255
Shadow=shadow
ItemShadowColor=0,0,0,1
Align=left
Xposition=15
DefaultFontSize=(#Height#/15-1)
Yposition=1.2

FontType=Segoe WP Semibold
FontTypeWP=Segoe WP
FontFaceUI=Segoe UI
FontFaceLight=Segoe WP Light