[StylExport]
SolidColor=0,022,255,1

y=r
x=(82)*#scaledpi#R
Antialias=1
MouseActionCursor=1
ToolTipText=#exporttheme# #currentsection#
Group=Export | Bye
Hidden=1
w=(30)*#scaledpi#






[e1]
Meter=Image
MeterStyle=StylExport
x=(50+200-30+#moveByX#)*#scaledpi#
y=(50+83+#moveByY#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\export#Item1HideSave#.png
LeftMouseUpAction=["#@#Common\MultiManager\Multimanager.exe" "#SETTINGSPATH#" "#SKINSPATH#" Zip 1 0]


[e2]
Meter=Image
MeterStyle=StylExport
x=(50+200*2-30+5+#moveByX#)*#scaledpi#
y=(50+83+#moveByY#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\export#Item2HideSave#.png
LeftMouseUpAction=["#@#Common\MultiManager\Multimanager.exe" "#SETTINGSPATH#" "#SKINSPATH#" Zip 2 0]

[e3]
Meter=Image
MeterStyle=StylExport
x=(50+200*3-30+10+#moveByX#)*#scaledpi#
y=(50+83+#moveByY#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\export#Item3HideSave#.png
LeftMouseUpAction=["#@#Common\MultiManager\Multimanager.exe" "#SETTINGSPATH#" "#SKINSPATH#" Zip 3 0]

[e4]
Meter=Image
MeterStyle=StylExport
x=(50+200-30+#moveByX#)*#scaledpi#
y=(50+118+83+#moveByY#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\export#Item4HideSave#.png
LeftMouseUpAction=["#@#Common\MultiManager\Multimanager.exe" "#SETTINGSPATH#" "#SKINSPATH#" Zip 4 0]

[e5]
Meter=Image
MeterStyle=StylExport
x=(50+200*2-30+5+#moveByX#)*#scaledpi#
y=(50+118+83+#moveByY#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\export#Item5HideSave#.png
LeftMouseUpAction=["#@#Common\MultiManager\Multimanager.exe" "#SETTINGSPATH#" "#SKINSPATH#" Zip 5 0]

[e6]
Meter=Image
MeterStyle=StylExport
x=(50+200*3-30+10+#moveByX#)*#scaledpi#
y=(50+118+83+#moveByY#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\export#Item6HideSave#.png
LeftMouseUpAction=["#@#Common\MultiManager\Multimanager.exe" "#SETTINGSPATH#" "#SKINSPATH#" Zip 6 0]

[e7]
Meter=Image
MeterStyle=StylExport
x=(50+200-30+#moveByX#)*#scaledpi#
y=(50+118*2+83+#moveByY#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\export#Item7HideSave#.png
LeftMouseUpAction=["#@#Common\MultiManager\Multimanager.exe" "#SETTINGSPATH#" "#SKINSPATH#" Zip 7 0]


[e8]
Meter=Image
MeterStyle=StylExport
y=(50+118*2+83+#moveByY#)*#scaledpi#
x=(50+200*2-30+5+#moveByX#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\export#Item8HideSave#.png
LeftMouseUpAction=["#@#Common\MultiManager\Multimanager.exe" "#SETTINGSPATH#" "#SKINSPATH#" Zip 8 0]

[e9]
Meter=Image
MeterStyle=StylExport
y=(50+118*2+83+#moveByY#)*#scaledpi#
x=(50+200*3-30+10+#moveByX#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\export#Item9HideSave#.png
LeftMouseUpAction=["#@#Common\MultiManager\Multimanager.exe" "#SETTINGSPATH#" "#SKINSPATH#" Zip 9 0]
