[StylShortcut]
SolidColor=0,022,255,1

y=r
x=(82)*#scaledpi#R
Antialias=1
MouseActionCursor=1
ToolTipText=#addshortcutfor# #currentsection#
Hidden=1
Group=Shortcut | Bye
w=(30)*#scaledpi#






[theme1]
Meter=Image
MeterStyle=StylShortcut
x=(50+30-30+#moveByX#)*#scaledpi#
y=(50+83+#moveByY#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\shortcut#Item1HideSave#.png
LeftMouseUpAction=[!ActivateConfig "WP7\Gallery\MultiManager\Shortcuts\1"]


[theme2]
Meter=Image
MeterStyle=StylShortcut
x=(50+100*2+0+5+#moveByX#)*#scaledpi#
y=(50+83+#moveByY#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\shortcut#Item2HideSave#.png
LeftMouseUpAction=[!ActivateConfig "WP7\Gallery\MultiManager\Shortcuts\2"]

[theme3]
Meter=Image
MeterStyle=StylShortcut
x=(50+200*2-0+10+#moveByX#)*#scaledpi#
y=(50+83+#moveByY#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\shortcut#Item3HideSave#.png
LeftMouseUpAction=["#@#Common\MultiManager\Multimanager.exe" "#SETTINGSPATH#" "#SKINSPATH#" Zip 3 0]

[theme4]
Meter=Image
MeterStyle=StylShortcut
x=(50+30-30+#moveByX#)*#scaledpi#
y=(50+118+83+#moveByY#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\shortcut#Item4HideSave#.png
LeftMouseUpAction=["#@#Common\MultiManager\Multimanager.exe" "#SETTINGSPATH#" "#SKINSPATH#" Zip 4 0]

[theme5]
Meter=Image
MeterStyle=StylShortcut
x=(50+200*1-0+5+#moveByX#)*#scaledpi#
y=(50+118+83+#moveByY#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\shortcut#Item5HideSave#.png
LeftMouseUpAction=["#@#Common\MultiManager\Multimanager.exe" "#SETTINGSPATH#" "#SKINSPATH#" Zip 5 0]

[theme6]
Meter=Image
MeterStyle=StylShortcut
x=(50+200*2-0+10+#moveByX#)*#scaledpi#
y=(50+118+83+#moveByY#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\shortcut#Item6HideSave#.png
LeftMouseUpAction=["#@#Common\MultiManager\Multimanager.exe" "#SETTINGSPATH#" "#SKINSPATH#" Zip 6 0]

[theme7]
Meter=Image
MeterStyle=StylShortcut
x=(50+30-30+#moveByX#)*#scaledpi#
y=(50+118*2+83+#moveByY#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\shortcut#Item7HideSave#.png
LeftMouseUpAction=["#@#Common\MultiManager\Multimanager.exe" "#SETTINGSPATH#" "#SKINSPATH#" Zip 7 0]


[theme8]
Meter=Image
MeterStyle=StylShortcut
y=(50+118*2+83+#moveByY#)*#scaledpi#
x=(50+200*1-0+5+#moveByX#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\shortcut#Item8HideSave#.png
LeftMouseUpAction=["#@#Common\MultiManager\Multimanager.exe" "#SETTINGSPATH#" "#SKINSPATH#" Zip 8 0]

[theme9]
Meter=Image
MeterStyle=StylShortcut
y=(50+118*2+83+#moveByY#)*#scaledpi#
x=(50+200*2-0+10+#moveByX#)*#scaledpi#
ImageName=#@#Graphics\TextItems\MultiManager\shortcut#Item9HideSave#.png
LeftMouseUpAction=["#@#Common\MultiManager\Multimanager.exe" "#SETTINGSPATH#" "#SKINSPATH#" Zip 9 0]
